language: cpp
dist: eoan
compiler: gcc

before_install:
  - eval "$(curl -sL https://raw.githubusercontent.com/ryuichis/oclint-cpp-travis-ci-examples/master/oclint-ci-install.sh)";
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-8
  # - sudo apt install libboost-filesystem-dev # needed for filesytem
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # GSL
  - sudo apt install libgsl-dev libgslcblas0
  # Codecov
  - sudo pip install codecov
  # OCLint
  # - ./install_oclint
  # valgrind, for helgrind and memcheck
  - sudo apt-get install -qq valgrind
  # SLOCcount
  - sudo apt-get install sloccount
  # proselint
  - sudo pip install proselint
  # Check dead links
  #- sudo apt-get install npm
  #- npm config set strict-ssl false
  #- sudo npm install -g markdown-link-check

script: 
  # Build and run the tests
  - qmake infomove.pro
  - make debug
  # - ./the_richel_setup_test
  # # helgrind
  # - valgrind --tool=helgrind --log-file=helgrind.log -v ./the_richel_setup_test
  # - cat helgrind.log
  # # memcheck
  # - valgrind --leak-check=full -v --show-reachable=yes --log-file=memcheck.log ./the_richel_setup_test
  # - cat memcheck.log
  # Build and run and profile normal program
  - qmake infomove.pro
  - make release
  # - time ./the_richel_setup
  # - gprof the_richel_setup > gprof.log
  # - head gprof.log -n 1000
  # Get code coverage
  # - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  # - ./do_oclint
  # proselint
  - proselint README.md
  # Get my folder
  - my_github=${PWD##*/}  
  # Check dead links
  #- ./scripts/check_dead_links
  # SLOCcount
  #   remove OCLint and .git, otherwise it will be counted as well
  - rm -rf oclint-0.10.3 oclint-0.10.3-x86_64-linux-3.13.0-74-generic.tar.gz oclint.log
  - rm -rf .git
  - rm -rf debug
  - rm -rf release
  - cd ..; sloccount --overhead 1 --personcost 22614 $my_github; cd $my_github

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)