---
editor_options:
  chunk_output_type: console
---

# Run an Infomove variant on the cluster

In this version, the evolved parameter D (aspiration) is also allowed to evolve.

## Prepare libraries

Libs remain the same in R.

```{r load_libs_v02, eval=FALSE}
# load libs
library(tidyverse)
library(ssh)
library(glue)
```

## Prepare infomove v02 on Peregrine

Check out the _allow_D_ branch on the cluster.

```{r prepare_infomove_v02, eval=FALSE}
# read peregrine password
password = read_lines("private/password.txt")

# connect to cluster and pull from master
s <- ssh_connect("p284074@peregrine.hpc.rug.nl", passwd = password)
ssh_exec_wait(s, command = c("cd infomove/",
                             "rm Makefile infomove",
                             "cd jobs",
                             "rm *.sh",
                             "rm *.out",
                             "cd ..",
                             "git pull",
                             "git checkout allow_D", # checkout the allow_D branch
                             "ml load GCC/8.3.0",
                             "ml load GSL/2.6-GCC-8.3.0",
                             "qmake infomove.pro",
                             "make clean -j4",
                             "make -j4"))
```

## Remove old data

```{r rem_old_data, eval=FALSE}
{
  ssh_exec_wait(s, c("cd infomove/data",
  'find . -name "*.csv" -type f -delete'))
}
```

## Run infomove

```{r use_infomover_run, eval=FALSE}
# read job shebang
shebang <- readLines("code_analysis/template_job.sh")

{
  type = c("info", "noinfo")
  phi = c(5, 25, 50, 100)
  rho = 0.1
  gens = "50000" # a test case
  timesteps = 100
  init_d = c(0.5) # D init at 0.5, unlike 1.0 to force following/switching
  n_lead = c(1,2,5)
  replicate = 1:5
}

sim_params <- crossing(type, phi, rho, gens, timesteps, init_d, n_lead, replicate)

# send commands
pwalk(sim_params, function(type, phi, rho, gens, timesteps,
                           init_d, n_lead, replicate){

  if(!dir.exists("jobs")){
    dir.create("jobs")
  }

  shebang[2] <- glue('#SBATCH --job-name=run_infomove_type-{type}_phi{phi}_nlead{n_lead}_rep{replicate}')
  {
    command <- glue('./infomove {type} {phi} {rho} {gens} {timesteps} {init_d} {n_lead} {replicate}')
    jobfile <- glue('job_infomove_type{type}_phi{phi}_nlead{n_lead}_rep{replicate}.sh')

    writeLines(c(shebang, command), con = glue('jobs/{jobfile}'))
    scp_upload(s, glue('jobs/{jobfile}'), to = "infomove/jobs/")
    file.remove(glue('jobs/{jobfile}'))
  }

  # run jobs; we are in infomove
  ssh_exec_wait(s, command = c("cd infomove/jobs",
                               glue('dos2unix {jobfile}'),
                               glue('sbatch {jobfile}')))
})
```

```{r, eval=FALSE}
# move into jobs, delete scripts and disconnect
ssh_exec_wait(s, command = c("cd infomove/jobs",
                             "rm *.sh *.out",
                             "cd .."))
ssh_disconnect(s)
```
