---
editor_options:
  chunk_output_type: console
---

# Run infomove on cluster

## Prepare libraries

```{r load_libs, eval=FALSE}
# load libs
library(tidyverse)
library(ssh)
library(glue)
```

## Prepare infomove on Peregrine

```{r prepare_infomove, eval=FALSE}
# read peregrine password
password = read_lines("private/password.txt")

# connect to cluster and pull from master
s <- ssh_connect("p284074@peregrine.hpc.rug.nl", passwd = password)
ssh_exec_wait(s, command = c("cd infomove/",
                             "cd jobs",
                             "rm *.sh",
                             "cd ..",
                             "git pull",
                             "ml load GCC/8.3.0",
                             "ml load GSL/2.6-GCC-8.3.0",
                             "qmake infomove.pro",
                             "make clean -j4",
                             "make -j4"))
```

## Run infomove

```{r use_infomover_run, eval=FALSE}
# prepare parameters
{
  type = c("noinfo", "info")
  phi = seq(5, 105, 20)
  rho = 0.1
  gens = "100000"
  timesteps = 100
  init_d = c(0.1, 0.5, 1.0)
  replicates = 1
}
sim_params = crossing()

# load R package on peregrine
ssh_exec_wait(s, command = c("cd infomove",
              "ml load R/3.6.1-foss-2018a",
              "R",
              glue::glue('infomover::run_infomove(
                        type=c({sprintf(toString(type))}),
                        phi=c({sprintf(toString(phi))}), 
                        rho=c({sprintf(toString(rho))}), 
                        gens=c({sprintf(toString(gens))}),
                        timesteps=({sprintf(toString(timesteps))}),
                        init_d=c({sprintf(toString(init_d))}),
                        replicates=c({sprintf(toString(replicates))}))')))

# move into jobs, delete scripts and disconnect
ssh_exec_wait(s, command = c("mv slurm* jobs",
                             "cd infomove/jobs",
                             "rm *.sh",
                             "mv data/*.csv ../data",
                             "cd .."))
ssh_disconnect(s)
```
