---
editor_options:
  chunk_output_type: console
---

```{r prep_libs_05, eval=FALSE}
# data libraries
library(readr)
library(dplyr)
library(purrr)
library(glue)
library(tidyr)

# plotting
library(ggplot2)
library(patchwork)
library(scico)
library(ggallin)
```

## Run local fitness landscape simulations

Install the package from GH.

```{r}
devtools::install_github("pratikunterwegs/infomover")
```

Run local FL code.

```{r eval=FALSE}
# run the damn infomove local fitness landscape
infomover::run_infomove_fl(type = c("info", "noinfo"),
                           phi = c(5, 25),
                           rho = 0.1,
                           timesteps = 100,
                           a_res = seq(-3, 3, 1),
                           b_res = seq(-3, 3, 1),
                           leader_choices = c(1,2,5),
                           gradient = 1,
                           n_rep = 5)
```

```{r summarise_fl_data, eval=FALSE}
# summarise the info data
infomover::print_fitness_landscape(data_path = "data",
                                       type = "info")
```

```{r}
# read in summary data
data = read_csv("data/info/data_fitness_landscape.csv")
```


```{r}
data = data %>% 
  # filter(res_a %in% c(-1,0,1),
  #        res_b %in% c(-1,0,1)) %>% 
  mutate(res_strat = glue::glue('res_a= {res_a}
                                res_b= {res_b}')) %>% 
  group_by(phi, leader_choices) %>% 
  nest()

# prepare palette
pal = scico(3, palette = "berlin", begin = 0.2, end = 0.8)

# prepare plots
 data = mutate(data,
              plot = pmap(list(phi, leader_choices, data), 
                          function(phi, leader_choices, data){
                plot = ggplot(data, 
                            aes(a,b))+
                  geom_tile(aes(fill = energy),
                            alpha = 0.3,
                            stat = "identity")+
                  # geom_tile(aes(res_a, res_b),
                  #           col = "black",
                  #           alpha = 0.1,
                  #           height = 1, width = 1,
                  #           fill = NA)+
                  scale_fill_gradient2(low = pal[1],
                                       mid = "white",
                                       high = pal[3])+
                  coord_cartesian(expand = FALSE)+
                  theme_bw(base_size = 6)+
                  facet_grid(~flr)+
                  labs(title = glue::glue('Φ (number of peaks): {phi}, simulation type: info'),
                       subtitle = glue::glue('# leader choices: {leader_choices}'))
              }))
```

```{r}
cairo_pdf(file = "figs/local_fitness_landscape_info.pdf", width = 10, height = 3,
            onefile = TRUE)
  {
    print(data$plot)
  }
  dev.off()
```


```{r prep_plot, eval=FALSE}
library(patchwork)
data = arrange(data, phi)
fig_list = wrap_plots(data$plot, ncol = 3)
```

